package muck.model;

/**
 * Represents a Bob CI/CD pipeline
 *
 * @param group  Pipeline group (defaults to "default" if null)
 * @param name   Pipeline name
 * @param status Pipeline status (defaults to "unknown" if null)
 */
public record Pipeline(String group, String name, String status) {

    /**
     * Compact constructor with default values
     */
    public Pipeline {
        group = group != null ? group : "default";
        status = status != null ? status : "unknown";
    }

    /**
     * Convenience constructor with default status
     */
    public Pipeline(String group, String name) {
        this(group, name, "unknown");
    }

    /**
     * Returns the full pipeline name in format: group/name
     */
    public String fullName() {
        return group + "/" + name;
    }

    /**
     * Creates a new Pipeline with updated status (records are immutable)
     */
    public Pipeline withStatus(String newStatus) {
        return new Pipeline(this.group, this.name, newStatus);
    }

    // Note: getters are automatically generated by record
    // getGroup(), getName(), getStatus() are all available
}
